// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductWebAPI.Data;

#nullable disable

namespace ProductWebAPI.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20251127133014_AddStudentCodeField")]
    partial class AddStudentCodeField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductWebAPI.Models.ContactInformation", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EmergencyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmergencyWorkplace")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GuardianNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ContactId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("ContactInformation", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.CurrentEducation", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AcademicUnit")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BacIICertificateCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BacIIGrade")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<int>("BacIIYear")
                        .HasColumnType("int");

                    b.Property<string>("CareerType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<string>("HighSchoolLocation")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HighSchoolName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("CurrentEducation", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.Enrollment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.Majors", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"));

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("MajorId");

                    b.ToTable("Majors", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Menus", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.PermanentAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AddressId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("PermanentAddress", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.RegisterInformation", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterId"));

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RegisterType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("RegisterId");

                    b.HasIndex("MajorId");

                    b.HasIndex("StudentId");

                    b.ToTable("RegisterInformation", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.StudentERM", b =>
                {
                    b.Property<string>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Telegram")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("StudentId");

                    b.ToTable("StudentEnrollment", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.Subjects", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("SubjectId");

                    b.HasIndex("MajorId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("OtpExpireTime")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProductWebAPI.Models.ContactInformation", b =>
                {
                    b.HasOne("ProductWebAPI.Models.StudentERM", "Student")
                        .WithOne("ContactInformation")
                        .HasForeignKey("ProductWebAPI.Models.ContactInformation", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProductWebAPI.Models.CurrentEducation", b =>
                {
                    b.HasOne("ProductWebAPI.Models.StudentERM", "Student")
                        .WithOne("CurrentEducation")
                        .HasForeignKey("ProductWebAPI.Models.CurrentEducation", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProductWebAPI.Models.Enrollment", b =>
                {
                    b.HasOne("ProductWebAPI.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductWebAPI.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProductWebAPI.Models.Payment", b =>
                {
                    b.HasOne("ProductWebAPI.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProductWebAPI.Models.PermanentAddress", b =>
                {
                    b.HasOne("ProductWebAPI.Models.StudentERM", "Student")
                        .WithOne("PermanentAddress")
                        .HasForeignKey("ProductWebAPI.Models.PermanentAddress", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProductWebAPI.Models.RegisterInformation", b =>
                {
                    b.HasOne("ProductWebAPI.Models.Majors", "Major")
                        .WithMany("RegisterInformations")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductWebAPI.Models.StudentERM", "Student")
                        .WithMany("RegisterInformations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProductWebAPI.Models.Subjects", b =>
                {
                    b.HasOne("ProductWebAPI.Models.Majors", "Major")
                        .WithMany("Subjects")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("ProductWebAPI.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("ProductWebAPI.Models.Majors", b =>
                {
                    b.Navigation("RegisterInformations");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ProductWebAPI.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ProductWebAPI.Models.StudentERM", b =>
                {
                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("CurrentEducation")
                        .IsRequired();

                    b.Navigation("PermanentAddress")
                        .IsRequired();

                    b.Navigation("RegisterInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
